# Generated by Django 3.2.13 on 2022-06-10 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_ninja_persona'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genin',
            fields=[
                ('ninja_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.ninja')),
                ('fecha_graduacion', models.DateField()),
                ('valoracion', models.CharField(max_length=200)),
            ],
            bases=('api.ninja',),
        ),
    ]
