# Generated by Django 3.2.13 on 2022-06-10 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_genin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chunin',
            fields=[
                ('ninja_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.ninja')),
                ('fecha_examen', models.DateField()),
                ('calificacion_examen', models.DateField()),
            ],
            bases=('api.ninja',),
        ),
        migrations.CreateModel(
            name='Jounin',
            fields=[
                ('ninja_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.ninja')),
                ('fecha_examen', models.DateField()),
                ('calificacion_examen', models.DateField()),
            ],
            bases=('api.ninja',),
        ),
    ]
