# Generated by Django 3.2.13 on 2022-06-10 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_chunin_jounin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('elemento', models.CharField(max_length=30)),
                ('es_oculta', models.BooleanField(default=False)),
                ('cantidad_chakra', models.IntegerField()),
            ],
        ),
    ]
