# Generated by Django 3.2.13 on 2022-06-10 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_tecnica'),
    ]

    operations = [
        migrations.CreateModel(
            name='TecnicaAtaque',
            fields=[
                ('tecnica_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.tecnica')),
                ('rango_ataque', models.IntegerField()),
            ],
            bases=('api.tecnica',),
        ),
        migrations.CreateModel(
            name='TecnicaCurativa',
            fields=[
                ('tecnica_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.tecnica')),
                ('velocidad_curacion', models.IntegerField()),
            ],
            bases=('api.tecnica',),
        ),
        migrations.CreateModel(
            name='NinjaTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ninja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ninja')),
                ('id_tecnica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tecnica')),
            ],
        ),
    ]
