# Generated by Django 3.2.13 on 2022-06-12 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_ninjatecnica_tecnicaataque_tecnicacurativa'),
    ]

    operations = [
        migrations.CreateModel(
            name='NinjaMedico',
            fields=[
                ('ninja_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.ninja')),
            ],
            bases=('api.ninja',),
        ),
    ]
