# Generated by Django 3.2.13 on 2022-06-12 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_ninjamedico'),
    ]

    operations = [
        migrations.CreateModel(
            name='BestiaMitica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=30)),
                ('invocador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ninja')),
            ],
        ),
    ]
