# Generated by Django 3.2.13 on 2022-06-13 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20220612_2357'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipoEnMisionPergamino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipoenmision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pergaminos', to='api.equipoenmision')),
                ('pergamino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos_en_mision', to='api.pergamino')),
            ],
        ),
        migrations.CreateModel(
            name='BestiaMisionPergaminoLlave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_bestia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.bestiamitica')),
                ('id_mision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mision')),
                ('id_pergamino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pergamino')),
            ],
        ),
    ]
