# Generated by Django 3.2.13 on 2022-06-13 02:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20220613_0249'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='ninja1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='exceptuar_ninja_1', to='api.ninja'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipo',
            name='ninja2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptuar_ninja_2', to='api.ninja'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='ninjamedico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ninjamedico'),
        ),
        migrations.AlterField(
            model_name='equipoenmisionpergamino',
            name='equipoenmision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.equipoenmision'),
        ),
        migrations.AlterField(
            model_name='equipoenmisionpergamino',
            name='pergamino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pergamino'),
        ),
        migrations.AlterField(
            model_name='ninjatecnica',
            name='ninja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ninja'),
        ),
        migrations.AlterField(
            model_name='ninjatecnica',
            name='tecnica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tecnica'),
        ),
        migrations.AlterUniqueTogether(
            name='equipo',
            unique_together={('ninja1', 'ninja2', 'ninjamedico')},
        ),
        migrations.AlterUniqueTogether(
            name='equipoenmisionpergamino',
            unique_together={('equipoenmision', 'pergamino')},
        ),
        migrations.AlterUniqueTogether(
            name='ninjatecnica',
            unique_together={('ninja', 'tecnica')},
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='ninja',
        ),
    ]
