# Generated by Django 3.2.13 on 2022-06-13 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20220613_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='clan',
            field=models.CharField(default='Konoha', max_length=50),
        ),
        migrations.AlterField(
            model_name='persona',
            name='edad',
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='persona',
            name='fecha_nacimiento',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nombre',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='persona',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('N', 'No se dice')], default='N', max_length=1),
        ),
    ]
