# Generated by Django 3.2.13 on 2022-06-13 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20220613_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestiamitica',
            name='nombre',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='bestiamitica',
            name='tipo',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='chunin',
            name='calificacion_examen',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='nombre',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='equipoenmision',
            name='cantidad_kunais',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='equipoenmision',
            name='cantidad_sellos',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='equipoenmision',
            name='cantidad_shurikens',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='equipoenmision',
            name='resultado',
            field=models.CharField(choices=[('S', 'Satisfactorio'), ('NS', 'No Satisfactorio'), ('P', 'Pendiente')], default='P', max_length=20),
        ),
        migrations.AlterField(
            model_name='genin',
            name='valoracion',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='jounin',
            name='calificacion_examen',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='mision',
            name='cliente',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='mision',
            name='pais_cliente',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='mision',
            name='rango',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='mision',
            name='recompensa',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ninja',
            name='sobrenombre',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='tecnica',
            name='cantidad_chakra',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tecnica',
            name='elemento',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='tecnica',
            name='nombre',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='tecnicaataque',
            name='rango_ataque',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tecnicacurativa',
            name='velocidad_curacion',
            field=models.IntegerField(default=0),
        ),
    ]
