# Generated by Django 3.2.13 on 2022-06-13 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20220613_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestiamitica',
            name='invocador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.ninja'),
        ),
    ]
