# Generated by Django 3.2.13 on 2022-06-13 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20220613_1025'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
